[#ftl]
[@c.page title="Dotazy"]
    <h1>Dotazy</h1>

    <h4>Zobrazit všechny posty</h4>
    <form action="/" method="get">
        <div class="row">
            <div class="ten columns">Seřazené sestupně podle data publikace
            </div>
            <div class="two columns submit">
                <button class="button-primary" type="submit">Zobrazit</button>
            </div>
        </div>
    </form>

[/@c.page]